require("lazy").setup({
    spec = {
        --{ import = "plugins.gruvbox" },
        --{ import = "plugins.tokyonight" },
        { import = "plugins.jb" },
        { import = "plugins.mason" },
        { import = "plugins.gitsigns" },
        { import = "plugins.telescope" },
        { import = "plugins.lspconfig" },
        { import = "plugins.cmp" },
        { import = "plugins.treesitter" },
        { import = "plugins.neotest" },
        { import = "plugins.neotest-java" },
        { import = "plugins.nerdtree" },
        { import = "plugins.which-key" },
        { import = "plugins.sqls" },
        { import = "plugins.conform" },
        { import = "plugins.dadbod" },
        { import = "plugins.autosession" },
    },
    checker = { enabled = true },
})
